export const Countries = [
  // { name: 'Afghanistan', alpha2: 'AF', numeric: '004' },
  { name: 'Åland Islands', alpha2: 'AX', numeric: '248' },
  { name: 'Albania', alpha2: 'AL', numeric: '008' },
  { name: 'Algeria', alpha2: 'DZ', numeric: '012' },
  { name: 'American Samoa', alpha2: 'AS', numeric: '016' },
  { name: 'Andorra', alpha2: 'AD', numeric: '020' },
  { name: 'Angola', alpha2: 'AO', numeric: '024' },
  { name: 'Anguilla', alpha2: 'AI', numeric: '660' },
  { name: 'Antarctica', alpha2: 'AQ', numeric: '010' },
  { name: 'Antigua and Barbuda', alpha2: 'AG', numeric: '028' },
  { name: 'Argentina', alpha2: 'AR', numeric: '032' },
  { name: 'Armenia', alpha2: 'AM', numeric: '051' },
  { name: 'Aruba', alpha2: 'AW', numeric: '533' },
  { name: 'Australia', alpha2: 'AU', numeric: '036' },
  { name: 'Austria', alpha2: 'AT', numeric: '040', vat: 0.2 },
  { name: 'Azerbaijan', alpha2: 'AZ', numeric: '031' },
  { name: 'Bahamas', alpha2: 'BS', numeric: '044' },
  { name: 'Bahrain', alpha2: 'BH', numeric: '048' },
  { name: 'Bangladesh', alpha2: 'BD', numeric: '050' },
  { name: 'Barbados', alpha2: 'BB', numeric: '052' },
  // { "name": "Belarus", "alpha2": "BY", "numeric": "112" },
  { name: 'Belgium', alpha2: 'BE', numeric: '056', vat: 0.21 },
  { name: 'Belize', alpha2: 'BZ', numeric: '084' },
  { name: 'Benin', alpha2: 'BJ', numeric: '204' },
  { name: 'Bermuda', alpha2: 'BM', numeric: '060' },
  { name: 'Bhutan', alpha2: 'BT', numeric: '064' },
  { name: 'Bolivia (Plurinational State of)', alpha2: 'BO', numeric: '068' },
  { name: 'Bonaire, Sint Eustatius and Saba', alpha2: 'BQ', numeric: '535' },
  { name: 'Bosnia and Herzegovina', alpha2: 'BA', numeric: '070' },
  { name: 'Botswana', alpha2: 'BW', numeric: '072' },
  { name: 'Bouvet Island', alpha2: 'BV', numeric: '074' },
  { name: 'Brazil', alpha2: 'BR', numeric: '076' },
  { name: 'British Indian Ocean Territory', alpha2: 'IO', numeric: '086' },
  { name: 'Brunei Darussalam', alpha2: 'BN', numeric: '096' },
  { name: 'Bulgaria', alpha2: 'BG', numeric: '100', vat: 0.2 },
  { name: 'Burkina Faso', alpha2: 'BF', numeric: '854' },
  { name: 'Burundi', alpha2: 'BI', numeric: '108' },
  { name: 'Cabo Verde', alpha2: 'CV', numeric: '132' },
  { name: 'Cambodia', alpha2: 'KH', numeric: '116' },
  { name: 'Cameroon', alpha2: 'CM', numeric: '120' },
  { name: 'Canada', alpha2: 'CA', numeric: '124' },
  { name: 'Cayman Islands', alpha2: 'KY', numeric: '136' },
  { name: 'Central African Republic', alpha2: 'CF', numeric: '140' },
  { name: 'Chad', alpha2: 'TD', numeric: '148' },
  { name: 'Chile', alpha2: 'CL', numeric: '152' },
  { name: 'China', alpha2: 'CN', numeric: '156' },
  { name: 'Christmas Island', alpha2: 'CX', numeric: '162' },
  { name: 'Cocos (Keeling) Islands', alpha2: 'CC', numeric: '166' },
  { name: 'Colombia', alpha2: 'CO', numeric: '170' },
  { name: 'Comoros', alpha2: 'KM', numeric: '174' },
  { name: 'Congo', alpha2: 'CG', numeric: '178' },
  // { "name": "Congo, Democratic Republic of the","alpha2": "CD","numeric": "180"},
  { name: 'Cook Islands', alpha2: 'CK', numeric: '184' },
  { name: 'Costa Rica', alpha2: 'CR', numeric: '188' },
  { name: "Côte d'Ivoire", alpha2: 'CI', numeric: '384' },
  { name: 'Croatia', alpha2: 'HR', numeric: '191', vat: 0.25 },
  // { "name": "Cuba", "alpha2": "CU", "numeric": "192" },
  { name: 'Curaçao', alpha2: 'CW', numeric: '531' },
  { name: 'Cyprus', alpha2: 'CY', numeric: '196', vat: 0.19 },
  { name: 'Czechia', alpha2: 'CZ', numeric: '203', vat: 0.21 },
  { name: 'Denmark', alpha2: 'DK', numeric: '208', vat: 0.25 },
  { name: 'Djibouti', alpha2: 'DJ', numeric: '262' },
  { name: 'Dominica', alpha2: 'DM', numeric: '212' },
  { name: 'Dominican Republic', alpha2: 'DO', numeric: '214' },
  { name: 'Ecuador', alpha2: 'EC', numeric: '218' },
  { name: 'Egypt', alpha2: 'EG', numeric: '818' },
  { name: 'El Salvador', alpha2: 'SV', numeric: '222' },
  { name: 'Equatorial Guinea', alpha2: 'GQ', numeric: '226' },
  { name: 'Eritrea', alpha2: 'ER', numeric: '232' },
  { name: 'Estonia', alpha2: 'EE', numeric: '233', vat: 0.2 },
  { name: 'Eswatini', alpha2: 'SZ', numeric: '748' },
  { name: 'Ethiopia', alpha2: 'ET', numeric: '231' },
  { name: 'Falkland Islands (Malvinas)', alpha2: 'FK', numeric: '238' },
  { name: 'Faroe Islands', alpha2: 'FO', numeric: '234' },
  { name: 'Fiji', alpha2: 'FJ', numeric: '242' },
  { name: 'Finland', alpha2: 'FI', numeric: '246', vat: 0.24 },
  { name: 'France', alpha2: 'FR', numeric: '250', vat: 0.2 },
  { name: 'French Guiana', alpha2: 'GF', numeric: '254' },
  { name: 'French Polynesia', alpha2: 'PF', numeric: '258' },
  { name: 'French Southern Territories', alpha2: 'TF', numeric: '260' },
  { name: 'Gabon', alpha2: 'GA', numeric: '266' },
  { name: 'Gambia', alpha2: 'GM', numeric: '270' },
  { name: 'Georgia', alpha2: 'GE', numeric: '268' },
  { name: 'Germany', alpha2: 'DE', numeric: '276', vat: 0.19 },
  { name: 'Ghana', alpha2: 'GH', numeric: '288' },
  { name: 'Gibraltar', alpha2: 'GI', numeric: '292' },
  { name: 'Greece', alpha2: 'GR', numeric: '300', vat: 0.24 },
  { name: 'Greenland', alpha2: 'GL', numeric: '304' },
  { name: 'Grenada', alpha2: 'GD', numeric: '308' },
  { name: 'Guadeloupe', alpha2: 'GP', numeric: '312' },
  { name: 'Guam', alpha2: 'GU', numeric: '316' },
  { name: 'Guatemala', alpha2: 'GT', numeric: '320' },
  { name: 'Guernsey', alpha2: 'GG', numeric: '831' },
  { name: 'Guinea', alpha2: 'GN', numeric: '324' },
  { name: 'Guinea-Bissau', alpha2: 'GW', numeric: '624' },
  { name: 'Guyana', alpha2: 'GY', numeric: '328' },
  { name: 'Haiti', alpha2: 'HT', numeric: '332' },
  { name: 'Heard Island and McDonald Islands', alpha2: 'HM', numeric: '334' },
  { name: 'Holy See', alpha2: 'VA', numeric: '336' },
  { name: 'Honduras', alpha2: 'HN', numeric: '340' },
  { name: 'Hong Kong', alpha2: 'HK', numeric: '344' },
  { name: 'Hungary', alpha2: 'HU', numeric: '348', vat: 0.27 },
  { name: 'Iceland', alpha2: 'IS', numeric: '352' },
  { name: 'India', alpha2: 'IN', numeric: '356' },
  { name: 'Indonesia', alpha2: 'ID', numeric: '360' },
  // { "name": "Iran (Islamic Republic of)","alpha2": "IR","numeric": "364"},
  // { "name": "Iraq", "alpha2": "IQ", "numeric": "368" },
  { name: 'Ireland', alpha2: 'IE', numeric: '372', vat: 0.23 },
  { name: 'Isle of Man', alpha2: 'IM', numeric: '833' },
  { name: 'Israel', alpha2: 'IL', numeric: '376' },
  { name: 'Italy', alpha2: 'IT', numeric: '380', vat: 0.22 },
  { name: 'Jamaica', alpha2: 'JM', numeric: '388' },
  { name: 'Japan', alpha2: 'JP', numeric: '392' },
  { name: 'Jersey', alpha2: 'JE', numeric: '832' },
  { name: 'Jordan', alpha2: 'JO', numeric: '400' },
  { name: 'Kazakhstan', alpha2: 'KZ', numeric: '398' },
  { name: 'Kenya', alpha2: 'KE', numeric: '404' },
  { name: 'Kiribati', alpha2: 'KI', numeric: '296' },
  // { "name": "Korea (Democratic People's Republic of)","alpha2": "KP","numeric": "408"},
  { name: 'Korea, Republic of', alpha2: 'KR', numeric: '410' },
  { name: 'Kuwait', alpha2: 'KW', numeric: '414' },
  { name: 'Kyrgyzstan', alpha2: 'KG', numeric: '417' },
  { name: "Lao People's Democratic Republic", alpha2: 'LA', numeric: '418' },
  { name: 'Latvia', alpha2: 'LV', numeric: '428', vat: 0.21 },
  { name: 'Lebanon', alpha2: 'LB', numeric: '422' },
  { name: 'Lesotho', alpha2: 'LS', numeric: '426' },
  { name: 'Liberia', alpha2: 'LR', numeric: '430' },
  { name: 'Libya', alpha2: 'LY', numeric: '434' },
  { name: 'Liechtenstein', alpha2: 'LI', numeric: '438' },
  { name: 'Lithuania', alpha2: 'LT', numeric: '440', vat: 0.21 },
  { name: 'Luxembourg', alpha2: 'LU', numeric: '442', vat: 0.16 },
  { name: 'Macao', alpha2: 'MO', numeric: '446' },
  { name: 'Madagascar', alpha2: 'MG', numeric: '450' },
  { name: 'Malawi', alpha2: 'MW', numeric: '454' },
  { name: 'Malaysia', alpha2: 'MY', numeric: '458' },
  { name: 'Maldives', alpha2: 'MV', numeric: '462' },
  { name: 'Mali', alpha2: 'ML', numeric: '466' },
  { name: 'Malta', alpha2: 'MT', numeric: '470', vat: 0.18 },
  { name: 'Marshall Islands', alpha2: 'MH', numeric: '584' },
  { name: 'Martinique', alpha2: 'MQ', numeric: '474' },
  { name: 'Mauritania', alpha2: 'MR', numeric: '478' },
  { name: 'Mauritius', alpha2: 'MU', numeric: '480' },
  { name: 'Mayotte', alpha2: 'YT', numeric: '175' },
  { name: 'Mexico', alpha2: 'MX', numeric: '484' },
  { name: 'Micronesia (Federated States of)', alpha2: 'FM', numeric: '583' },
  { name: 'Moldova, Republic of', alpha2: 'MD', numeric: '498' },
  { name: 'Monaco', alpha2: 'MC', numeric: '492', vat: 0.2 },
  { name: 'Mongolia', alpha2: 'MN', numeric: '496' },
  { name: 'Montenegro', alpha2: 'ME', numeric: '499' },
  { name: 'Montserrat', alpha2: 'MS', numeric: '500' },
  { name: 'Morocco', alpha2: 'MA', numeric: '504' },
  { name: 'Mozambique', alpha2: 'MZ', numeric: '508' },
  { name: 'Myanmar', alpha2: 'MM', numeric: '104' },
  { name: 'Namibia', alpha2: 'NA', numeric: '516' },
  { name: 'Nauru', alpha2: 'NR', numeric: '520' },
  { name: 'Nepal', alpha2: 'NP', numeric: '524' },
  { name: 'Netherlands', alpha2: 'NL', numeric: '528', vat: 0.21 },
  { name: 'New Caledonia', alpha2: 'NC', numeric: '540' },
  { name: 'New Zealand', alpha2: 'NZ', numeric: '554' },
  { name: 'Nicaragua', alpha2: 'NI', numeric: '558' },
  { name: 'Niger', alpha2: 'NE', numeric: '562' },
  { name: 'Nigeria', alpha2: 'NG', numeric: '566' },
  { name: 'Niue', alpha2: 'NU', numeric: '570' },
  { name: 'Norfolk Island', alpha2: 'NF', numeric: '574' },
  { name: 'North Macedonia', alpha2: 'MK', numeric: '807' },
  { name: 'Northern Mariana Islands', alpha2: 'MP', numeric: '580' },
  { name: 'Norway', alpha2: 'NO', numeric: '578' },
  { name: 'Oman', alpha2: 'OM', numeric: '512' },
  { name: 'Pakistan', alpha2: 'PK', numeric: '586' },
  { name: 'Palau', alpha2: 'PW', numeric: '585' },
  { name: 'Palestine, State of', alpha2: 'PS', numeric: '275' },
  { name: 'Panama', alpha2: 'PA', numeric: '591' },
  { name: 'Papua New Guinea', alpha2: 'PG', numeric: '598' },
  { name: 'Paraguay', alpha2: 'PY', numeric: '600' },
  { name: 'Peru', alpha2: 'PE', numeric: '604' },
  { name: 'Philippines', alpha2: 'PH', numeric: '608' },
  { name: 'Pitcairn', alpha2: 'PN', numeric: '612' },
  { name: 'Poland', alpha2: 'PL', numeric: '616', vat: 0.23 },
  { name: 'Portugal', alpha2: 'PT', numeric: '620', vat: 0.23 },
  { name: 'Portugal - Azores', alpha2: 'PT-20', numeric: '6202', vat: 0.16 },
  { name: 'Portugal - Madeira', alpha2: 'PT-30', numeric: '6203', vat: 0.22 },
  { name: 'Puerto Rico', alpha2: 'PR', numeric: '630' },
  { name: 'Qatar', alpha2: 'QA', numeric: '634' },
  { name: 'Réunion', alpha2: 'RE', numeric: '638' },
  { name: 'Romania', alpha2: 'RO', numeric: '642', vat: 0.19 },
  // { "name": "Russian Federation", "alpha2": "RU", "numeric": "643" },
  { name: 'Rwanda', alpha2: 'RW', numeric: '646' },
  { name: 'Saint Barthélemy', alpha2: 'BL', numeric: '652' },
  { name: 'Saint Helena, Ascension and Tristan da Cunha', alpha2: 'SH', numeric: '654' },
  { name: 'Saint Kitts and Nevis', alpha2: 'KN', numeric: '659' },
  { name: 'Saint Lucia', alpha2: 'LC', numeric: '662' },
  { name: 'Saint Martin (French part)', alpha2: 'MF', numeric: '663' },
  { name: 'Saint Pierre and Miquelon', alpha2: 'PM', numeric: '666' },
  { name: 'Saint Vincent and the Grenadines', alpha2: 'VC', numeric: '670' },
  { name: 'Samoa', alpha2: 'WS', numeric: '882' },
  { name: 'San Marino', alpha2: 'SM', numeric: '674' },
  { name: 'Sao Tome and Principe', alpha2: 'ST', numeric: '678' },
  { name: 'Saudi Arabia', alpha2: 'SA', numeric: '682' },
  { name: 'Senegal', alpha2: 'SN', numeric: '686' },
  { name: 'Serbia', alpha2: 'RS', numeric: '688' },
  { name: 'Seychelles', alpha2: 'SC', numeric: '690' },
  { name: 'Sierra Leone', alpha2: 'SL', numeric: '694' },
  { name: 'Singapore', alpha2: 'SG', numeric: '702' },
  { name: 'Sint Maarten (Dutch part)', alpha2: 'SX', numeric: '534' },
  { name: 'Slovakia', alpha2: 'SK', numeric: '703', vat: 0.2 },
  { name: 'Slovenia', alpha2: 'SI', numeric: '705', vat: 0.22 },
  { name: 'Solomon Islands', alpha2: 'SB', numeric: '090' },
  { name: 'Somalia', alpha2: 'SO', numeric: '706' },
  { name: 'South Africa', alpha2: 'ZA', numeric: '710' },
  { name: 'South Georgia and the South Sandwich Islands', alpha2: 'GS', numeric: '239' },
  // { "name": "South Sudan", "alpha2": "SS", "numeric": "728" },
  { name: 'Spain', alpha2: 'ES', numeric: '724', vat: 0.21 },
  { name: 'Sri Lanka', alpha2: 'LK', numeric: '144' },
  // { "name": "Sudan", "alpha2": "SD", "numeric": "729" },
  { name: 'Suriname', alpha2: 'SR', numeric: '740' },
  { name: 'Svalbard and Jan Mayen', alpha2: 'SJ', numeric: '744' },
  { name: 'Sweden', alpha2: 'SE', numeric: '752', vat: 0.25 },
  { name: 'Switzerland', alpha2: 'CH', numeric: '756' },
  // { "name": "Syrian Arab Republic", "alpha2": "SY", "numeric": "760" },
  { name: 'Taiwan, Province of China', alpha2: 'TW', numeric: '158' },
  { name: 'Tajikistan', alpha2: 'TJ', numeric: '762' },
  { name: 'Tanzania, United Republic of', alpha2: 'TZ', numeric: '834' },
  { name: 'Thailand', alpha2: 'TH', numeric: '764' },
  { name: 'Timor-Leste', alpha2: 'TL', numeric: '626' },
  { name: 'Togo', alpha2: 'TG', numeric: '768' },
  { name: 'Tokelau', alpha2: 'TK', numeric: '772' },
  { name: 'Tonga', alpha2: 'TO', numeric: '776' },
  { name: 'Trinidad and Tobago', alpha2: 'TT', numeric: '780' },
  { name: 'Tunisia', alpha2: 'TN', numeric: '788' },
  { name: 'Turkey', alpha2: 'TR', numeric: '792' },
  { name: 'Turkmenistan', alpha2: 'TM', numeric: '795' },
  { name: 'Turks and Caicos Islands', alpha2: 'TC', numeric: '796' },
  { name: 'Tuvalu', alpha2: 'TV', numeric: '798' },
  { name: 'Uganda', alpha2: 'UG', numeric: '800' },
  { name: 'Ukraine (excl. Occupied Territories)', alpha2: 'UA', numeric: '804' },
  { name: 'United Arab Emirates', alpha2: 'AE', numeric: '784' },
  { name: 'United Kingdom of Great Britain and Northern Ireland', alpha2: 'GB', numeric: '826' },
  { name: 'United States of America', alpha2: 'US', numeric: '840' },
  { name: 'United States Minor Outlying Islands', alpha2: 'UM', numeric: '581' },
  { name: 'Uruguay', alpha2: 'UY', numeric: '858' },
  { name: 'Uzbekistan', alpha2: 'UZ', numeric: '860' },
  { name: 'Vanuatu', alpha2: 'VU', numeric: '548' },
  { name: 'Venezuela (Bolivarian Republic of)', alpha2: 'VE', numeric: '862' },
  { name: 'Viet Nam', alpha2: 'VN', numeric: '704' },
  { name: 'Virgin Islands (British)', alpha2: 'VG', numeric: '092' },
  { name: 'Virgin Islands (U.S.)', alpha2: 'VI', numeric: '850' },
  { name: 'Wallis and Futuna', alpha2: 'WF', numeric: '876' },
  { name: 'Western Sahara', alpha2: 'EH', numeric: '732' },
  { name: 'Yemen', alpha2: 'YE', numeric: '887' },
  { name: 'Zambia', alpha2: 'ZM', numeric: '894' },
  // { "name": "Zimbabwe", "alpha2": "ZW", "numeric": "716" }
]
